name: ${project.name}
version: ${project.version}
main: studio.magemonkey.fabled.Fabled
provides:
  - SkillAPI
  - ProSkillAPI
api-version: '1.19'
authors:
  - Travja
  - goflish
  - Eniripsa96
  - Sentropic
has-open-classloader: true

dependencies:
  server:
    CodexCore:
      load: BEFORE
      required: true
    Vault:
      load: BEFORE
      required: false
    Citizens:
      load: BEFORE
      required: false
    LibsDisguises:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    NoCheatPlus:
      load: BEFORE
      required: false
    MythicMobs:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false
    WorldEdit:
      load: BEFORE
      required: false
    Mimic:
      load: BEFORE
      required: false
load-before:
  - name: Divinity
    boostrap: false
  - name: Quests
    boostrap: false
  - name: TAB
    boostrap: false

permissions:
  fabled.basic:
    description: access to skill trees and using skills
    default: true
  fabled.reset:
    description: access to resetting your class
    default: true
  fabled.exp:
    description: access to gaining exp
    default: true
  fabled.level:
    description: access to using the level and exp commands
    default: op
  fabled.mana:
    description: access to using the mana command
    default: op
  fabled.points:
    description: access to using the points command
    default: op
  fabled.reload:
    description: access to using the reload command
    default: op
  fabled.class:
    description: access to all classes
    default: op
  fabled.skill:
    description: access to all skills
    default: op
  fabled.lore:
    description: access to all lore commands
    default: op
  fabled.force:
    description: access to force commands
    default: op
  fabled.attrib:
    description: access to giving attribute points
    default: op
  fabled.gui:
    description: access to GUI editor menu
    default: op

  fabled.*:
    description: access to all commands and features
    default: op
    children:
      fabled.basic: true
      fabled.reset: true
      fabled.exp: true
      fabled.level: true
      fabled.mana: true
      fabled.points: true
      skillapi.reload: true
      skillapi.class: true
      skillapi.skill: true
      skillapi.lore: true
      skillapi.gui: true
